---
- name: Import remi GPG key.
  ansible.builtin.rpm_key:
    key: "{{ remi_repo_8_gpg_key_url }}"
    state: present

- name: Check if remi repo is already installed
  ansible.builtin.shell: dnf repolist enabled | grep -q '^remi'
  register: remi_installed
  changed_when: false
  ignore_errors: true

- name: Install remi repo on CentOS Stream 8 if not installed
  ansible.builtin.dnf:
    name: "{{ remi_repo_url_8 }}"
    state: present
  async: 60
  poll: 0
  register: async_result
  when:
    - remi_installed.rc != 0

- name: Set changed status if remi repo was already installed
  ansible.builtin.set_fact:
    changed: true
  when:
    - remi_installed.rc == 0

- name: Check if remi repo installation is complete on CentStream 8
  ansible.builtin.async_status:
    jid: "{{ async_result.ansible_job_id }}"
  register: job_result
  retries: 10
  delay: 60
  until: job_result.finished | default(false)
  when:
    - remi_installed.rc != 0
