---
- name: Verify
  hosts: all

  tasks:
    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Check OS version
      ansible.builtin.command: cat /etc/redhat-release
      register: os_version
      changed_when: false

    - name: Print the package facts
      ansible.builtin.debug:
        var: ansible_facts.packages

    - name: Show OS version
      ansible.builtin.debug:
        var: os_version
